// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfEfXQ0LdP9ccdtmu2aTzUDS0RBbOIrbQ',
    appId: '1:167727860132:web:981d9e15f05ddbdd925931',
    messagingSenderId: '167727860132',
    projectId: 'flowrist-driver',
    authDomain: 'flowrist-driver.firebaseapp.com',
    storageBucket: 'flowrist-driver.firebasestorage.app',
    measurementId: 'G-TQ2YCFGLCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1_nGhKDqJUPAQDmPrT_BCutok6Qh3r1I',
    appId: '1:167727860132:android:6a936335632f3d69925931',
    messagingSenderId: '167727860132',
    projectId: 'flowrist-driver',
    storageBucket: 'flowrist-driver.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1fim_cBu9p3wDVaZcqWudK4g3tesw3YI',
    appId: '1:167727860132:ios:b9af80db38bbf084925931',
    messagingSenderId: '167727860132',
    projectId: 'flowrist-driver',
    storageBucket: 'flowrist-driver.firebasestorage.app',
    iosBundleId: 'com.example.trackingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1fim_cBu9p3wDVaZcqWudK4g3tesw3YI',
    appId: '1:167727860132:ios:b9af80db38bbf084925931',
    messagingSenderId: '167727860132',
    projectId: 'flowrist-driver',
    storageBucket: 'flowrist-driver.firebasestorage.app',
    iosBundleId: 'com.example.trackingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfEfXQ0LdP9ccdtmu2aTzUDS0RBbOIrbQ',
    appId: '1:167727860132:web:249da647f8f1040d925931',
    messagingSenderId: '167727860132',
    projectId: 'flowrist-driver',
    authDomain: 'flowrist-driver.firebaseapp.com',
    storageBucket: 'flowrist-driver.firebasestorage.app',
    measurementId: 'G-PN8CMYXZ21',
  );
}
